from django.core.management.base import BaseCommand
from constructionapp.models import Product


class Command(BaseCommand):
    help = 'Seed the database with sample products'

    def handle(self, *args, **kwargs):
        # Clear existing products
        Product.objects.all().delete()
        
        products = [
            # Cement Products
            {
                'name': 'Ultratech OPC 53 Grade Cement',
                'slug': 'ultratech-opc-53',
                'category': 'cement',
                'sub_category': 'OPC',
                'description': 'Premium quality Ordinary Portland Cement suitable for all general construction work. High strength and durability.',
                'price': 380.00,
                'unit': 'bag',
                'stock': 5000,
                'is_available': True,
            },
            {
                'name': 'Ambuja PPC Cement',
                'slug': 'ambuja-ppc',
                'category': 'cement',
                'sub_category': 'PPC',
                'description': 'Portland Pozzolana Cement with excellent workability and resistance to chemical attacks. Ideal for marine structures.',
                'price': 350.00,
                'unit': 'bag',
                'stock': 4500,
                'is_available': True,
            },
            {
                'name': 'Birla White Cement',
                'slug': 'birla-white',
                'category': 'cement',
                'sub_category': 'WHITE',
                'description': 'Premium white cement for decorative finishes, tiles, and mosaic work. Superior whiteness and fineness.',
                'price': 550.00,
                'unit': 'bag',
                'stock': 2000,
                'is_available': True,
            },
            {
                'name': 'ACC Gold Cement',
                'slug': 'acc-gold',
                'category': 'cement',
                'sub_category': 'OPC',
                'description': 'Premium grade cement with advanced composite technology for high early strength.',
                'price': 370.00,
                'unit': 'bag',
                'stock': 4000,
                'is_available': True,
            },
            
            # Sand Products
            {
                'name': 'River Sand - Fine',
                'slug': 'river-sand-fine',
                'category': 'sand',
                'sub_category': 'RIVER',
                'description': 'Natural river sand for plastering and finishing work. Clean and free from impurities.',
                'price': 45.00,
                'unit': 'cubic feet',
                'stock': 10000,
                'is_available': True,
            },
            {
                'name': 'M-Sand (Manufactured Sand)',
                'slug': 'm-sand',
                'category': 'sand',
                'sub_category': 'M_SAND',
                'description': 'Engineered sand manufactured from crushed stone. Perfect alternative to river sand.',
                'price': 35.00,
                'unit': 'cubic feet',
                'stock': 15000,
                'is_available': True,
            },
            {
                'name': 'Plastering Sand',
                'slug': 'plastering-sand',
                'category': 'sand',
                'sub_category': 'P_SAND',
                'description': 'Specially graded sand for plastering work. Fine particles for smooth finish.',
                'price': 40.00,
                'unit': 'cubic feet',
                'stock': 8000,
                'is_available': True,
            },
            {
                'name': 'Concrete Sand',
                'slug': 'concrete-sand',
                'category': 'sand',
                'sub_category': 'C_SAND',
                'description': 'Coarse sand for concrete work and foundation. Well graded and clean.',
                'price': 38.00,
                'unit': 'cubic feet',
                'stock': 12000,
                'is_available': True,
            },
            
            # Steel Products
            {
                'name': 'TMT Bars Fe 500D',
                'slug': 'tmt-fe-500d',
                'category': 'steel',
                'sub_category': 'TMT',
                'description': 'Thermo Mechanically Treated bars with superior strength and ductility. ISI certified.',
                'price': 52000.00,
                'unit': 'ton',
                'stock': 500,
                'is_available': True,
            },
            {
                'name': 'TMT Bars Fe 415',
                'slug': 'tmt-fe-415',
                'category': 'steel',
                'sub_category': 'FE415',
                'description': 'High ductility TMT bars ideal for earthquake resistant structures.',
                'price': 48000.00,
                'unit': 'ton',
                'stock': 400,
                'is_available': True,
            },
            {
                'name': 'TMT Bars Fe 550',
                'slug': 'tmt-fe-550',
                'category': 'steel',
                'sub_category': 'FE550',
                'description': 'High strength TMT bars for heavy construction projects.',
                'price': 55000.00,
                'unit': 'ton',
                'stock': 300,
                'is_available': True,
            },
            {
                'name': 'Structural Steel Channels',
                'slug': 'steel-channels',
                'category': 'steel',
                'sub_category': 'STRUCTURAL',
                'description': 'MS Channels for structural framework and industrial applications.',
                'price': 48000.00,
                'unit': 'ton',
                'stock': 200,
                'is_available': True,
            },
            
            # Bricks
            {
                'name': 'Red Clay Bricks',
                'slug': 'red-clay-bricks',
                'category': 'brick',
                'sub_category': 'CLAY',
                'description': 'Traditional red bricks for wall construction. Kiln fired for durability.',
                'price': 8.00,
                'unit': 'piece',
                'stock': 500000,
                'is_available': True,
            },
            {
                'name': 'Fly Ash Bricks',
                'slug': 'fly-ash-bricks',
                'category': 'brick',
                'sub_category': 'FLYASH',
                'description': 'Eco-friendly bricks made from fly ash. Light weight and uniform size.',
                'price': 12.00,
                'unit': 'piece',
                'stock': 300000,
                'is_available': True,
            },
            {
                'name': 'Solid Concrete Blocks',
                'slug': 'solid-concrete-blocks',
                'category': 'brick',
                'sub_category': 'CONCRETE',
                'description': 'Solid concrete blocks for load bearing walls. High compressive strength.',
                'price': 45.00,
                'unit': 'piece',
                'stock': 100000,
                'is_available': True,
            },
            {
                'name': 'Hollow Concrete Blocks',
                'slug': 'hollow-concrete-blocks',
                'category': 'brick',
                'sub_category': 'HOLLOW',
                'description': 'Hollow blocks for partition walls. Light weight and thermal insulation.',
                'price': 35.00,
                'unit': 'piece',
                'stock': 80000,
                'is_available': True,
            },
            
            # Aggregates
            {
                'name': '20mm Aggregate',
                'slug': 'aggregate-20mm',
                'category': 'aggregate',
                'sub_category': 'COARSE',
                'description': '20mm crushed stone aggregate for concrete work.',
                'price': 850.00,
                'unit': 'ton',
                'stock': 5000,
                'is_available': True,
            },
            {
                'name': '10mm Aggregate',
                'slug': 'aggregate-10mm',
                'category': 'aggregate',
                'sub_category': 'COARSE',
                'description': '10mm crushed stone for concrete and asphalt work.',
                'price': 900.00,
                'unit': 'ton',
                'stock': 4000,
                'is_available': True,
            },
            {
                'name': 'Gitti (Stone Grit)',
                'slug': 'gitti-stone-grit',
                'category': 'aggregate',
                'sub_category': 'GITTI',
                'description': 'Stone grit for flooring and driveway applications.',
                'price': 750.00,
                'unit': 'ton',
                'stock': 3000,
                'is_available': True,
            },
            
            # Hardware
            {
                'name': 'Binding Wire',
                'slug': 'binding-wire',
                'category': 'hardware',
                'sub_category': 'WIRE',
                'description': 'GI binding wire for tying reinforcement bars.',
                'price': 80.00,
                'unit': 'kg',
                'stock': 5000,
                'is_available': True,
            },
            {
                'name': 'Steel Door Frame',
                'slug': 'steel-door-frame',
                'category': 'hardware',
                'sub_category': 'DOOR',
                'description': 'Ready made steel door frame for main doors.',
                'price': 1200.00,
                'unit': 'piece',
                'stock': 500,
                'is_available': True,
            },
            {
                'name': 'Plywood 19mm',
                'slug': 'plywood-19mm',
                'category': 'hardware',
                'sub_category': 'PLYWOOD',
                'description': 'BWR grade plywood 19mm thickness for furniture and construction.',
                'price': 2500.00,
                'unit': 'sheet',
                'stock': 1000,
                'is_available': True,
            },
        ]
        
        for product_data in products:
            Product.objects.create(**product_data)
        
        self.stdout.write(self.style.SUCCESS(f'Successfully created {len(products)} products'))
