# Generated by Django 6.0 on 2026-01-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField()),
                ('prod_price', models.ImageField(upload_to='')),
                ('prod_description', models.CharField()),
            ],
        ),
    ]
