# Generated by Django 6.0 on 2026-01-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_price',
            field=models.FloatField(),
        ),
    ]
