# Generated by Django 6.0 on 2026-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('sand', 'Sand'), ('steel', 'Steel'), ('bricks', 'Bricks'), ('pipes', 'Steel Pipes')], max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='materials/')),
            ],
        ),
    ]
