# Generated by Django 6.0 on 2026-02-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
